shellscape/jsx-email

- .eslintignore
- packages/heading/src/heading.spec.tsx
- packages/heading/src/utils/spaces.ts
- packages/heading/src/utils/utils.spec.ts
- shared/tsconfig.default.json
- Fix `withMargin` and `withSpace` utils
- Add tests for utils
> feat(heading): fix utils and add tests

- pnpm-lock.yaml
- shared/vitest.config.ts
Repo
- Add explicit types to vitest config
> chore(repo): add explicit types to vitest config

- apps/web/src/index.md
`Quick start` button in docs leads to 404 due to trailing `/`
> fix(docs): fix quick-start url typo

- docs/quick-start.md
> fix(docs): fix superstructjs docs link

- apps/demo/emails/airbnb-review.tsx
- apps/demo/emails/codepen-challengers.tsx
- apps/demo/emails/dropbox-reset-password.tsx
- apps/demo/emails/github-access-token.tsx
- apps/demo/emails/koala-welcome.tsx
- apps/demo/emails/linear-login-code.tsx
- apps/demo/emails/stripe-welcome.tsx
- apps/demo/emails/yelp-recent-login.tsx
- apps/demo/staged/netlify-welcome.tsx
- apps/demo/staged/vercel-invite-user.tsx
- docs/components/button.md
- packages/button/README.md
- packages/button/src/button.tsx
- packages/cli/src/assets/email.mustache
Removes unused properties from component Props type, updates docs.
> fix(button): remove pX and pY from types

- README.md
> fix(readme): update typo in readme.md

- package.json
- packages/cli/app/src/main.tsx
- packages/cli/app/vite.config.ts
- packages/cli/package.json
- packages/cli/src/commands/preview.ts
- pnpm-lock.yaml
This reworks the dynamic imports in the vite implementation of the CLI preview tool so that it functions properly outside of the jsx-email repo.
> fix(cli): rework the dynamic imports for the preview tool

- CONTRIBUTING.md
- docs/core/cli.md
- packages/cli/src/commands/help.ts
I noticed a couple of typos in the cli help, plus associated documentation. Plus a small typo on the `CONTRIBUTING.md` page
> fix(cli): typos on cli and documentation

- packages/cli/src/index.ts
Add `shebang` at the beginning of a script. 
It's a special line that tells the operating system how to execute the script. In this case, it's commonly used in Node.js scripts.
> fix(cli): add shebang to cli script

- packages/tailwind/src/tailwind.tsx
- packages/tailwind/test/.snapshots/tailwind.test.tsx.snap
- packages/tailwind/test/tailwind.test.tsx
`processHead()` was previously returning `child` instead of `processedChild`, leading to duplicated output when using `<Tailwind />`
> fix(tailwind): incorrect variable reference in processHead()

- .gitignore
- docs/core/cli.md
- packages/cli/package.json
- packages/cli/src/commands/build.ts
- pnpm-lock.yaml
This PR adds a Client Compatibility check to the `email build` command via a `--check` flag.
> feat(cli): add client compatibility check

- packages/cli/app/src/home.tsx
Link on the preview homepage to the documentation currently still points to react-email package instead of this one. If this is intended feel free to close this PR.
> fix(cli): update link to documentation in preview home page

- docs/core/cli.md
- packages/cli/src/commands/build.ts
Updates the usage examples of `email build` to show directories can be used as input.
Fixes the default `props` used with `email build`
> fix(cli): clarify build examples, set default props correctly

- docs/faq/known-issues.md
This PR contains: A new FAQ section for Known issues (currently `Next.js` issues)
Adds a FAQ section with Known issues for two `Next.js` issues:
- Next.js webpack does not support importing `.mjs` files
- Build error `x await isn't allowed in non-async function`
> docs: Added known issues FAQ

- docs/email-providers.md
Docs
This PR adds a [Plunk](https://www.useplunk.com/) example to the `email-providers` section in the documentation
> feat(docs): add plunk to email providers

- docs/faq.md
Fixes some minor typos in the FAQ document.
Also added a section with information on why a minimal repro is required, plus links to help create a repro.
> docs: Fix typos in FAQ, add section on creating a reproduction

- docs/components/tailwind.md
List any relevant issue numbers: N/A
Reflects the recent rename of the `Tailwind` component `isProduction` flag to `production` instead.
> docs: Tailwind `isProduction` rename to `production`

- README.md
- docs/email-providers.md
Docs
This PR updates the Plunk integration example and adds Plunk to email providers on introduction page
> chore(docs): add Plunk to providers and update integration code

- apps/test/fixtures/base.jsx
- apps/test/tests/.snapshots/smoke.spec.ts-page-Base-1-chromium.txt
- docs/components/conditional.md
- packages/jsx-email/src/components/body.tsx
- packages/jsx-email/src/components/conditional.tsx
- packages/jsx-email/src/index.ts
- packages/jsx-email/src/render/process.ts
- packages/jsx-email/src/types.ts
- packages/jsx-email/test/.snapshots/conditional.test.tsx.snap
- packages/jsx-email/test/conditional.test.tsx
This PR adds a new `Conditional` component to the project which renders conditional HTML comments such like 
```html
```
> feat(jsx-email): add Conditional (mso) component

- apps/preview/app/src/main.tsx
- apps/test/fixtures/empty.tsx
Fixes #125 
Adds some code to handle and edge case with empty files in the target preview directory.
> fix(app-preview): ignore empty modules

- apps/web/.vitepress/config.mts
- apps/web/.vitepress/theme/custom.css
- apps/web/package.json
- apps/web/src/api/contributions.data.ts
- apps/web/src/contributions.md
- pnpm-lock.yaml
App-web
This PR adds a `contributions` page to the jsx-email website. It will serve as a showcase of the latest contributions to the project and the project contributors
> feat(app-web): add contributions page

- docs/components/image.md
> docs: fix import.meta property in image component

- apps/preview/app/src/components/sidebar.tsx
This PR contains: A fix for comparing the filesystem path versus the browser path
This is a small change to update the logic for comparing the active preview in the sidebar.
> fix(app-preview): Updates sidebar comparison logic

- apps/preview/app/src/main.tsx
- packages/jsx-email/src/cli/commands/preview.ts
> fix(jsx-email): inject target path for preview app

- apps/preview/app/src/main.tsx
This PR naturally sorts files and directories.
> fix(app-preview): naturally sort directories

- apps/preview/app/src/app.ts
- apps/preview/app/src/config.ts
- apps/preview/app/src/helpers.ts
- apps/preview/app/src/main.tsx
- apps/preview/app/src/routes.tsx
- apps/preview/app/src/templates.ts
- apps/preview/index.d.ts
- apps/preview/index.js
- apps/preview/package.json
- apps/test/tests/smoke.spec.ts
- pnpm-lock.yaml
This PR adds support for using an exclude glob to omit files from the preview app.
BREAKING CHANGES: This introduces `micromatch` as a dependency and requires a vite configuration change in `jsx-email`. This will also be incompatible with prior versions of the package.
> feat(app-preview)!: add exclude glob support

- apps/demo/emails/airbnb-review.tsx
- apps/demo/emails/apple-receipt.tsx
- apps/demo/emails/codepen-challengers.tsx
- apps/demo/emails/credential emails/dropbox-reset-password.tsx
- apps/demo/emails/credential emails/github-access-token.tsx
- apps/demo/emails/credential emails/linear-login-code.tsx
- apps/demo/emails/credential emails/magic links/notion-magic-link.tsx
- apps/demo/emails/credential emails/magic links/raycast-magic-link.tsx
- apps/demo/emails/credential emails/twitch-reset-password.tsx
- apps/demo/emails/google-play-policy-update.tsx
- apps/demo/emails/nike-receipt.tsx
- apps/demo/emails/plaid-verify-identity.tsx
- apps/demo/emails/slack-confirm.tsx
- apps/demo/emails/stack-overflow-tips.tsx
- apps/demo/emails/vercel-invite-user.tsx
- apps/demo/emails/welcome emails/koala-welcome.tsx
- apps/demo/emails/welcome emails/netlify-welcome.tsx
- apps/demo/emails/welcome emails/stripe-welcome.tsx
- apps/demo/emails/yelp-recent-login.tsx
- apps/demo/tsconfig.json
Preparing for the v2.0.0 release, updating the demo templates to use named exports.
> chore(repo): update demos to named exports

- apps/preview/README.md
> docs: fix typo in apps/preview readme

- packages/jsx-email/src/cli/commands/build.ts
- packages/jsx-email/test/debug.test.tsx
- packages/jsx-email/test/render/render.test.tsx
This PR adds support for building email templates using `email build` where templates reside in nested directories from the root directory passed.
> fix(jsx-email): cli build nested files

- packages/jsx-email/src/components/tailwind/tailwind.tsx
- packages/jsx-email/test/render/.snapshots/render.test.tsx.snap
- packages/jsx-email/test/render/fixtures/tailwind.tsx
- scripts/test.tsx
- scripts/tester.tsx
List any relevant issue numbers: fixes 162
Enforces media query mode for darkmode Tailwind variants.
> fix(jsx-email): assert media query for Tailwind dark mode variants

- packages/minify-preset/moon.yml
- packages/minify-preset/package.json
- packages/minify-preset/src/index.ts
- packages/minify-preset/tsup.config.ts
- pnpm-lock.yaml
Introduces a new minify preset for rehype that doesn't rely on uglifyjs, which does not play well with serverless environments
> feat(minify-preset)!: initial release

- .github/workflows/validate.yml
- packages/jsx-email/package.json
- packages/jsx-email/src/render/process.ts
- pnpm-lock.yaml
Sets up jsx-email to use the new custom minify preset. Should be slightly faster and this removes some incompatible bits (namely uglifyjs) from the bundle for lambda and serverless compat.
> fix(jsx-email): use custom minify preset

- apps/preview/app/src/components/nav.tsx
- apps/preview/app/src/components/send.tsx
- apps/preview/app/src/components/shell.tsx
- apps/preview/app/src/components/sidebar.tsx
app-preview
Solves #181 
This PR adds the necessary logic and ui updates for a mobile sidebar in the email preview
> feat(app-preview): add logic for mobile sidebar and update ui

- packages/jsx-email/package.json
- pnpm-lock.yaml
jsx-email
Fixes a bug with quotes in custom styles (e.g `font: "Roberto Pro", sans-serif`)
> chore(jsx-email): bump md-to-react-email dep

- packages/jsx-email/src/cli/commands/build.ts
resolves #194 
This pull fixed the currently broken build process on Windows.
> fix(jsx-email): build process broken on Windows, fixes #194

- packages/jsx-email/package.json
- packages/jsx-email/src/renderer/move-style.ts
- packages/jsx-email/src/renderer/render.ts
- packages/plugin-pretty/package.json
- pnpm-lock.yaml
> fix(jsx-email): resolve type issues breaking `jsx-email` build

- docs/email-providers.md
update SES example to v2 API https://github.com/sst/ion/blob/dev/examples/aws-jsx-email/index.ts
> chore(docs): update SES to v2 API

- assets/templates/email.mustache
- packages/jsx-email/src/cli/commands/create.mts
Some general cleanup and correction for the `email create` command after we moved to an ESM binary.
> fix(jsx-email): create command esm fix

- packages/create-jsx-email/src/index.ts
Create-jsx-email
Fixes #237 
This PR updates the template path imported in the `create-jsx-email` script
> fix(create-jsx-email): update template path in create-jsx-email script

- apps/preview/app/src/components/nav-button.tsx
- apps/preview/app/src/components/nav.tsx
- apps/preview/app/src/main.tsx
- apps/preview/app/src/routes.tsx
- apps/preview/app/src/templates.ts
- apps/preview/app/src/types.ts
- apps/preview/index.d.ts
- apps/preview/index.js
- apps/preview/package.json
- pnpm-lock.yaml
BREAKING CHANGES: This PR introduces changes to how preview template data is loaded from the local filesystem and is not backwards compatible.
Significant performance improvements as the loading of template data is improved. Fixes the template nav animation in the preview.
> fix(app-preview)!: improve performance, fix nav animation

- packages/jsx-email/src/cli/commands/preview.mts
- test/smoke/tests/smoke.test.ts
Well, not sure how the smoke tests passed with this problem being an actual problem, but running the preview apparently needs a few more optimized deps for vite.
> fix(jsx-email): optimize cookie, set-cookie-parser for vite

- docs/components/raw.md
- packages/jsx-email/src/index.ts
The component is actually not exported from the library. Added an export.
Also removed a leftover from the component docs. 
> fix(jsx-email): export Raw component + docs fixes

- docs/faq.md
> chore(repo): add React context use to FAQ

- docs/core/render.md
List any relevant issue numbers: none
the name of the parameter is `inlineCss`, not `inline`
> chore(repo): Update render docs to refer to correct option name

- .github/actions/setup/action.yml
- .github/workflows/release.yml
- .github/workflows/test-cli.yml
- .github/workflows/test-smoke.yml
- .github/workflows/test-v18.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- .moon/toolchain.yml
- package.json
- pnpm-lock.yaml
Updating workflows and the pnpm version in the repo.
> chore(repo): update pnpm and workflows

- docs/core/compile.md
Update variable name in example code to align with API of `compile`
> docs: fix typo in compile.md

- apps/preview/package.json
- packages/jsx-email/package.json
List any relevant issue numbers: 
resolves #297
bump `react-router-dom` version. unsure if this causes any issues.
> chore(jsx-email): upgrade react-router-dom to 7.5.2 due to high severity vuln
